### ISSUE TITLE
DLC als Mod whitelisten !!!

### ISSUE THREAD

**Issue by Kili-97** [TacticalBaconDevs/TBUploader#2]
Dringend für Freitag!!

**Comment by Kili-97** [comment]
-mod=Contact
-mod=GM

**Comment by Kili-97** [comment]
obwohl wenn man es wie obenschreibt meckert er nicht ^^

**Comment by shukari** [comment]
also gehts?
Kann sein, das wir es normal starten müssen, weil der TBUploader sowas nicht kann

**Comment by Kili-97** [comment]
ne geht leider nicht
